name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Zip
        uses: montudor/action-zip@v1
        with:
          args: zip --recurse-patterns godot-editor-debugger.zip "addons/**/*"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: godot-editor-debugger.zip